# **10 minutes to pandas**
* https://pandas.pydata.org/docs/user_guide/10min.html
* pip install numpy, pandas

In [1]:
import numpy  as np
import pandas as pd

## **Basic data structures (기본구조)**

* <font color=red> <b> Series: 1차(one-dimensional) 데이터
* <font color=red> <b> DataFrame: 2차(two-dimensional) 데이터 (like table)
* [N]차 : N차원을 말하는 것

<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*OaUbgSxKnC_kaRj0H6vK5Q.jpeg" widcth=400>

<pre>      단일값[0]       리스트, 튜플, 딕[1]        Series[1]              Dataframe[2]                        Tensor[3]

In [2]:
(5) + 10    #(5) = 단일값

15

In [3]:
# row vector : 리스트/튜플/딕처럼 가로로 출력
# column vector : 세로로 출력

## **C : 생성**

In [4]:
mylist = pd.Series([1, 3, 5, np.nan, 6, 8])
print(mylist)

s = pd.Series(mylist)
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [5]:
mylist = [ [1, 3, 5, np.nan, 6, 8] ,
           [1, 3, 5, np.nan, 6, 8] ,
           [1, 3, 5, np.nan, 6, 8] 
         ]

df = pd.DataFrame (mylist)
print(df)

   0  1  2   3  4  5
0  1  3  5 NaN  6  8
1  1  3  5 NaN  6  8
2  1  3  5 NaN  6  8

In [6]:
mylist = [ [1, 3, 5, np.nan, 6, 8] ,
           [1, 3, 5, np.nan, 6, 8] ,
           [1, 3, 5, np.nan, 6, 8]    # nan = 없는값, 입력/수정 안 되는 진짜 없는 거 (여러 행열 중에 non이 하나라도 있으면 아예 연산 불가)
         ]

df = pd.DataFrame (mylist, index=[10,20,30], columns=['a','b','c','d','e','f'])   # 각 행열에 네이밍
print(df)

df   #print 없이 하면 진짜 표처럼 예쁘게!

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

In [7]:
df.dtypes

a      int64
b      int64
c      int64
d    float64
e      int64
f      int64
dtype: object

In [8]:
mydict = { "a":[1,1,1], "b":[3,3,3], "c":[5,5,5] }      #컬럼 네이밍을 abc로 지정해버림 ( i&c 불필요)
df = pd.DataFrame(mydict)
df

   a  b  c
0  1  3  5
1  1  3  5
2  1  3  5

In [9]:
mylist2 = [ [1, 2, 3],
            [2, 3, 4],
            [3, 4, 5] ]
df = pd.DataFrame(mylist2)
df

   0  1  2
0  1  2  3
1  2  3  4
2  3  4  5

In [10]:
mydict2 = { "title":"ddd", "a":[2,4,6], "N":["dd", "ss", "ff"] }
df = pd.DataFrame(mydict2)
df

  title  a   N
0   ddd  2  dd
1   ddd  4  ss
2   ddd  6  ff

## **Viewing data**

In [11]:
df.head()

  title  a   N
0   ddd  2  dd
1   ddd  4  ss
2   ddd  6  ff